### PR TITLE
Create zh_tw.json

### PR DESCRIPTION
**Pull request by yappy2000d**

### CODE REVIEW

**Comment by Corail31** [comment]
Hi Yappy2000d, thank you a lot for this translation, i suppose it's ready for merge ?
NB : you can contact me on curseForge if you want the "contributor bonus" in game :)

**Comment by yappy2000d** [comment]
I think there is basically no problem, it's time to merge it! :D

**Comment by yappy2000d** [comment]
After continually admiring my own tomb one night, I prefer the type of tombstone is tombstone. :)
By the way,it’s strange in our culture, it's unlucky to arrange funerals while still alive.But it's needless to say that this is really cool for me.:satisfied:

**Comment by yappy2000d** [comment]
Hope this will not delay you for too long. My game ID is yappy2000.Thank you for proventing such a great mod!:blush:

**Comment by Corail31** [comment]
About the choice of graves, it was initially an idea of the mod of Die Classy from Subaraki (Absolem Jackdaw) that is also the artist who made the voodoo poppet for Tombstone. It's also why the advancement is now named "Die Classy" :)
It is more done in an aesthetic context and that players like to be able to configure certain things even when it is on a dedicated server.
NB : i forgot to add your translation in the new release but will be the next one :)

**Pull request merged**
